### ISSUE TITLE
Example?

### ISSUE THREAD

**Issue by Czop122345** [Velka-DEV/Gotane#7]
Pls

**Comment by cth-latest** [comment]
Hi @Czop122345, it's been a long time, but I will respond here to provide some information for future readers.

I don't offer any support for the Gotane library, nor for Miellax. They are intended to be used by informed individuals because, without proper authorization, the use of these libraries can be malicious. I assume informed users can easily understand how the libraries work.

Perhaps I'll change my mind later, but that's the current stance.
